### ISSUE TITLE
Braze SDK causes a circular reference

### ISSUE THREAD

**Issue by chrisdp** [braze-inc/braze-roku-sdk#2]
Due to the Braze SDK Task storing a reference to `m.top` in it's instance of the Braze "class" it is impossible to clean up the SDK. Happy to work with you on a solution to this.

**Comment by bryanlogan** [comment]
I've sent you an email to the address on your GitHub profile to discuss this more. Thanks.

**Comment by bryanlogan** [comment]
This has been fixed in the 1.0.0 release.
